<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/1999/REC-html401-19991224/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
<title>Mail de facture</title>
<style>
@media only screen and (max-width: 300px) {
body {
    width: 218px !important;
    margin: auto !important;
}
.table {
    width: 195px !important;
    margin: auto !important;
}
.logo, .titleblock, .linkbelow, .box, .footer, .space_footer {
    width: auto !important;
    display: block !important;
}
span.title {
    font-size: 20px !important;
    line-height: 23px !important
}
span.subtitle {
    font-size: 14px !important;
    line-height: 18px !important;
    padding-top: 10px !important;
    display: block !important;
}
td.box p {
    font-size: 12px !important;
    font-weight: bold !important;
}
.table-recap table, .table-recap thead, .table-recap tbody, .table-recap th, .table-recap td, .table-recap tr {
    display: block !important;
}
.table-recap {
    width: 200px!important;
}
.table-recap tr td, .conf_body td {
    text-align: center !important;
}
.address {
    display: block !important;
    margin-bottom: 10px !important;
}
.space_address {
    display: none !important;
}
}

@media only screen and (min-width: 301px) and (max-width: 500px) {
body {
    width: 308px!important;
    margin: auto!important;
}
.table {
    width: 285px!important;
    margin: auto!important;
}
.logo, .titleblock, .linkbelow, .box, .footer, .space_footer {
    width: auto!important;
    display: block!important;
}
.table-recap table, .table-recap thead, .table-recap tbody, .table-recap th, .table-recap td, .table-recap tr {
    display: block !important;
}
.table-recap {
    width: 295px !important;
}
.table-recap tr td, .conf_body td {
    text-align: center !important;
}
}

@media only screen and (min-width: 501px) and (max-width: 768px) {
body {
    width: 478px!important;
    margin: auto!important;
}
.table {
    width: 450px!important;
    margin: auto!important;
}
.logo, .titleblock, .linkbelow, .box, .footer, .space_footer {
    width: auto!important;
    display: block!important;
}
}

@media only screen and (max-device-width: 480px) {
body {
    width: 308px!important;
    margin: auto!important;
}
.table {
    width: 285px;
    margin: auto!important;
}
.logo, .titleblock, .linkbelow, .box, .footer, .space_footer {
    width: auto!important;
    display: block!important;
}
.table-recap {
    width: 295px!important;
}
.table-recap tr td, .conf_body td {
    text-align: center!important;
}
.address {
    display: block !important;
    margin-bottom: 10px !important;
}
.space_address {
    display: none !important;
}
}
</style>
</head>


<body leftmargin="0" marginwidth="0" topmargin="0" marginheight="0" offset="0" style="background-color: #f7f7f7; padding: 0; text-align: center;" bgcolor="#f7f7f7">
<table width="100%" id="outer_wrapper" style="background-color: #f7f7f7;" bgcolor="#f7f7f7">
  <tr>
    <td><!-- Deliberately empty to support consistent sizing and layout across multiple email clients. --></td>
    <td width="600"><div id="wrapper" dir="ltr" style="margin: 0 auto; padding: 70px 0; width: 100%; max-width: 600px; -webkit-text-size-adjust: none;" width="100%">
        <table border="0" cellpadding="0" cellspacing="0" height="100%" width="100%">
          <tr>
            <td align="center" valign="top"><div id="template_header_image">
                <p style="margin-top: 0;"><img src="https://ci3.googleusercontent.com/meips/ADKq_NZCpaVRlrEd60GNBfRO3ToEX76_Kwxlh4C-1BzKJj0N1pB3ORmB22F11gT1V2lwcadvyE_BKNqVCODgUQSdst-URGN1gXNylzsi30V5wsv_wnUs_3YktCItQg=s0-d-e1-ft#https://ombriere.com/wp-content/uploads/email/logo-ombriere-mail.png" alt="Les Ombrières de Provence" style="border: none; display: inline-block; font-size: 14px; font-weight: bold; height: auto; outline: none; text-decoration: none; text-transform: capitalize; vertical-align: middle; max-width: 100%; margin-left: 0; margin-right: 0;" border="0"></p>
              </div>
              <table border="0" cellpadding="0" cellspacing="0" width="100%" id="template_container" style="background-color: #fff; border: 1px solid #dedede; box-shadow: 0 1px 4px rgba(0,0,0,.1); border-radius: 3px;" bgcolor="#fff">
                <tr>
                  <td align="center" valign="top"><!-- Header -->
                    
                    <table border="0" cellpadding="0" cellspacing="0" width="100%" id="template_header" style='background-color: #e08224; color: #fff; border-bottom: 0; font-weight: bold; line-height: 100%; vertical-align: middle; font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif; border-radius: 3px 3px 0 0;' bgcolor="#e08224">
                      <tr>
                        <td id="header_wrapper" style="padding: 36px 48px; display: block;"><h1 style='font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif; font-size: 30px; font-weight: 300; line-height: 150%; margin: 0; text-align: left; text-shadow: 0 1px 0 #857069; color: #fff; background-color: inherit;' bgcolor="inherit">Les Ombrières de Provence</h1></td>
                      </tr>
                    </table>
                    
                    <!-- End Header --></td>
                </tr>
                <tr>
                  <td align="center" valign="top"><!-- Body -->
                    
                    <table border="0" cellpadding="0" cellspacing="0" width="100%" id="template_body">
                      <tr>
                        <td valign="top" id="body_content" style="background-color: #fff;" bgcolor="#fff"><!-- Content -->
                          
                          <table border="0" cellpadding="20" cellspacing="0" width="100%">
                            <tr>
							
                              <td valign="top" style="padding: 48px 48px 32px;"><div id="body_content_inner" style='color: #636363; font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif; font-size: 14px; line-height: 150%; text-align: left;' align="left">
								  <h2 style='font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif; font-size: 16px; text-transform:uppercase; font-weight: 300; line-height: 150%; margin: 0; text-align: left; color: #e08224; background-color: inherit;' bgcolor="inherit">Demande de rappel prospect - produit sur mesure</h2>
                                 <p data-html-only="1" style="border-bottom:1px solid #D6D4D4;margin:3px 0 7px;font-weight:500;padding-bottom:10px"> 
									 

        <p>Une demande de chiffrage a été déposée sur le site, voici le détail</p>
        <ul>
             <li><strong>Type de projet :</strong><?= libTypeProduit( $mail_typeproduit ) ?></li>
             <li><strong>Quantité :</strong> <?= $mail_quantite ?></li>
             
             <li><strong>Longueur :</strong> <?= $mail_longueur ?> m</li>
             <li><strong>Largeur :</strong> <?= $mail_largeur ?> m</li>
             <li><strong>Matière :</strong> <?= libMatiere( $mail_matiere ) ?></li>
             <li><strong>Espacement traverses (si pergola):</strong><?= libTraverse($mail_traverse) ?></li>
             <li><strong>Boucles (si rideau):</strong><?= libTraverse($mail_boucles) ?></li>
            <li><strong>Ourlet :</strong> <?= $mail_ourlet ? 'Oui' : 'Non' ?></li>
           
            <li><strong>Option premium :</strong><?= $mail_premium ? 'Oui' : 'Non'?> </li>
            <li><strong>Email client :</strong> <?= $mail_mailclient ?></li>
            <li><strong>Coordonnées client / Description projet :</strong><?= $mail_infoClient ?></li>
            <li><strong>Montant estimé :</strong> <?= number_format($mail_prix, 2, ',', '') ?> €</li>
            <li><strong>Numéro de la demande JotForm :</strong><?php echo $mail_jot_form_id; ?></li>


        </ul>
        <br/>
        
                                  <br />
                                  Bonne journée,<br />
                                  <br />
                                  Le site internet - contact@ombriere.com <br />
                                  <br />
                                  </p>
                                </div></td>
                            </tr>
                          </table>
                          
                          <!-- End Content --></td>
                      </tr>
                    </table>
                    
                    <!-- End Body --></td>
                </tr>
              </table></td>
          </tr>
          <tr>
            <td align="center" valign="top"><!-- Footer -->
              
              <table border="0" cellpadding="10" cellspacing="0" width="100%" id="template_footer">
                <tr>
                  <td valign="top" style="padding: 0; border-radius: 6px;"><table border="0" cellpadding="10" cellspacing="0" width="100%">
                      <tr>
                        <td colspan="2" valign="middle" id="credit" style='border-radius: 6px; border: 0; color: #8a8a8a; font-family: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif; font-size: 12px; line-height: 150%; text-align: center; padding: 24px 0;' align="center"><p style="margin: 0 0 16px;"><a href="https://ombriere.com/" style="color:#337ff1">https://ombriere.com/</a></p></td>
                      </tr>
                    </table></td>
                </tr>
              </table>
              
              <!-- End Footer --></td>
          </tr>
        </table>
      </div></td>
    <td><!-- Deliberately empty to support consistent sizing and layout across multiple email clients. --></td>
  </tr>
</table>
</body>
</html>
        